export const badges = [
  "Sales Cloud Rollout Strategy",
  "Salesforce B2C Commerce Project Management",
  "API Basics",
  "Accessibility Basics",
  "Account Data Strategies",
  "Accountability & Delegation",
  "Accounts & Contacts for Lightning Experience",
  "Accounts & Contacts for Salesforce Classic",
  "Action Plans in Financial Services Cloud",
  "Administrator Certification Maintenance (Spring '19)",
  "Administrator Certification Maintenance (Summer ’18)",
  "Administrator Certification Maintenance (Summer ’19)",
  "Administrator Certification Maintenance (Winter ’19)",
  "Administrator Certification Prep: Applications, Activities, and Mobile",
  "Administrator Certification Prep: Reporting and Automation",
  "Administrator Certification Prep: Security and Data Management",
  "Administrator Certification Prep: Setup and Objects",
  "Advanced Formulas",
  "Advanced Territory Management",
  "Advertising Studio Implementation",
  "Advertising Studio Implementation Basics",
  "Alexa Development Basics",
  "Alignment with Your Manager",
  "Analytics Administration Basics",
  "Analytics App Design",
  "Analytics App Template Development",
  "Analytics Apps Basics",
  "Analytics Basics",
  "Analytics Dashboard Building Basics",
  "Analytics Dashboard Navigation",
  "Analytics Data Integration Basics",
  "Apex & .NET Basics",
  "Apex Basics & Database",
  "Apex Basics for Admins",
  "Apex Enterprise Patterns: Domain & Selector Layers",
  "Apex Enterprise Patterns: Service Layer",
  "Apex Integration Services",
  "Apex Metadata API",
  "Apex Testing",
  "Apex Triggers",
  "App Customization Lite",
  "App Development Without Limits",
  "App Licensing and Customer Support for AppExchange",
  "App Logic Vulnerability Prevention",
  "App Upgrading for AppExchange",
  "AppExchange App Development",
  "AppExchange App Selling",
  "AppExchange App Strategy",
  "AppExchange App Trial Management",
  "AppExchange Basics",
  "AppExchange Checkout",
  "AppExchange Partner Basics",
  "AppExchange Partner Business Planning",
  "AppExchange Security Review",
  "AppExchange Solutions",
  "Application Lifecycle and Development Models",
  "Architecture of Salesforce B2C Commerce",
  "Artificial Intelligence Basics",
  "Artificial Intelligence for Customer Service",
  "Asynchronous Apex",
  "Atlassian Agile Basics",
  "Atlassian Overview of Agile Frameworks",
  "Audience Segmentation",
  "Audience Studio Basics",
  "Aura Components Basics",
  "Aura Components Core Concepts",
  "Aura Components Skills & Tools",
  "Aura Components Tips & Gotchas",
  "B2B Marketing Analytics Basics",
  "B2B Marketing Analytics Basics for Lightning App",
  "B2C Commerce Developer Certification Maintenance (Spring '18)",
  "B2C Commerce Developer Certification Maintenance (Spring '19)",
  "Big Object Basics",
  "Blockchain Basics",
  "Brand Alignment in Distributed Organizations",
  "Branded Mobile Apps with Mobile Publisher",
  "Business Experimentation",
  "CPQ Specialist Certification Maintenance (Spring '18)",
  "CPQ Specialist Certification Maintenance (Spring ’19)",
  "CRM for Salesforce Classic",
  "Call Center Integration for Lightning Experience",
  "Campaign Basics",
  "Campaign Management with Nonprofit Success Pack",
  "Career Development Planning",
  "Case Feed",
  "Change Data Capture Basics",
  "Change Set Development Model",
  "Channel Management and Partner Portal Strategy",
  "Channel Order App Basics",
  "Channel Sales for Partners",
  "Chatter Administration for Lightning Experience",
  "Chatter Administration for Salesforce Classic",
  "Chatter for Lightning Experience",
  "Client List Growth with Financial Services Cloud",
  "Client Management with Financial Services Cloud",
  "Coaching & Feedback",
  "Coding for Web Accessibility",
  "Collaborative Forecasts Configuration",
  "Collaborative Forecasts Setup",
  "Commerce Cloud Basics",
  "Commerce Cloud Einstein Implementation",
  "Commerce Cloud Features",
  "Communication Skills for Customer Service Agents",
  "Communities in Financial Services Cloud",
  "Community Cloud Basics",
  "Community Rollout Strategy",
  "Community Search Basics",
  "Company-Wide Org Settings",
  "Competitor Tracking in Salesforce",
  "Configurable Bundles in Salesforce CPQ",
  "Connected App Basics",
  "Constituent Data Management with Nonprofit Success Pack",
  "Consulting Partner Basics",
  "Consumer Interaction Management",
  "Contact Builder Implementation",
  "Contact Center Design and Setup",
  "Contact Center Leadership for Executives",
  "Contact Center Operations",
  "Contact Center Transformation",
  "Contact and Account Settings in Nonprofit Success Pack",
  "Content Builder Basics",
  "Content Builder Block SDK",
  "Content Builder Email Personalization for Partners",
  "Content Builder Features",
  "Content Publishing with Social Studio",
  "Continuous Integration Using Salesforce DX",
  "Culture of Feedback",
  "Custom Metadata Types Basics",
  "Customer Data Management for Modern Marketers",
  "Customer Journey Basics",
  "Customer Retention for Managers",
  "Customer Service in the Fourth Industrial Revolution",
  "Customer Success Strategies for AppExchange Partners",
  "Customer-Centric Data Strategies",
  "Customer-Centric Discovery for Salesforce Partners",
  "Cyber Hygiene",
  "Cyber Resilience"
];
